%define snapdate 20101114

Summary: An SCIM port of android Google Pinyin IME
Name: scim-googlepinyin
Version: 0.1
Release: %mkrel -c %snapdate 1
License: ASL 2.0
Group: System/Internationalization
URL: http://code.google.com/p/scim-googlepinyin/
# source0 is generated by:
# git clone git://github.com/tchaikov/scim-googlepinyin.git
# cd scim-googlepinyin
# git archive --format=tar --prefix=scim-googlepinyin/ HEAD | xz> scim-googlepinyin-%{snapdate}.tar.xz
Source: %{name}-%{snapdate}.tar.xz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
BuildRequires: scim-devel >= 1.4.8
Requires: scim-client

%description
scim-googlepinyin is an SCIM port of google-pinyin on android platform.
It's basically a translation from its original java code to C++ counterpart.
Android google pinyin's core is not changed in porting, but this user
interface is slightly modified to simulate the bevaviour of GooglePinyin
on Windows.

%prep
%setup -qn %{name}

%build
./autogen.sh
%configure2_5x --disable-static
%make

%install
rm -rf $RPM_BUILD_ROOT
%makeinstall_std

rm -fr %buildroot/%{scim_plugins_dir}/*/*.la

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{_datadir}/scim/googlepinyin
%{_datadir}/scim/icons/google-pinyin_icon.png
%{scim_plugins_dir}/*/*.so


%changelog
* Fri Dec 24 2010 Funda Wang <fwang@mandriva.org> 0.1-0.20101114.1mdv2011.0
+ Revision: 624572
- new snapshot

* Fri Dec 03 2010 Oden Eriksson <oeriksson@mandriva.com> 0.1-0.20091231.2mdv2011.0
+ Revision: 607519
- rebuild

* Sun Jan 03 2010 Funda Wang <fwang@mandriva.org> 0.1-0.20091231.1mdv2010.1
+ Revision: 485769
- new version 20091231

* Sat Dec 26 2009 Funda Wang <fwang@mandriva.org> 0.1-0.20091225.1mdv2010.1
+ Revision: 482553
- import scim-googlepinyin


